name: Linters

on: ["push", "pull_request"]

# test

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        #os: [windows-latest]
        python: [2.7, 3.13]
    steps:

    - uses: actions/checkout@v4

    - name: Install python ${{ matrix.python }} with LisardByte/setup_python action
      if: matrix.python <= 2.7
      uses: LizardByte/actions/actions/setup_python@master
      with:
        python-version: ${{ matrix.python }}

    - name: Install python ${{ matrix.python }} with standard setup-python action
      if: matrix.python > 2.7
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Build wheel and install
      run: |
        pip install -U setuptools wheel build
        make build
        mv sandbox backup_sandbox
        mv dist/*.whl dist/sandbox-0.0.1-py2.py3-none-any.whl
        pip install -U "sandbox[pyquery] @ file://$(pwd)/dist/sandbox-0.0.1-py2.py3-none-any.whl"

    - name: Run tests
      run: |
        python -V
        python test.py
